import { SELL_BOND_ADDRESS as SELL_BOND_ADDRESS_V1, SELL_BOND_ABI as SELL_BOND_ABI_V1 } from './sellBondContractV1';
import { SELL_BOND_ADDRESS as SELL_BOND_ADDRESS_V2, SELL_BOND_ABI as SELL_BOND_ABI_V2 } from './sellBondContractV2';

export { SELL_BOND_ADDRESS_V1, SELL_BOND_ABI_V1, SELL_BOND_ADDRESS_V2, SELL_BOND_ABI_V2 };

export const SELL_BOND_ADDRESS = SELL_BOND_ADDRESS_V2;
export const SELL_BOND_ABI = SELL_BOND_ABI_V2;

