import { useEffect, useState } from 'react';
import { fetchJson } from '../utils/fetchJson';
import { fetchBondsV2TotalsSafe } from '../utils/bondsV2Json';
import type { UseBondsV2VolumeResult } from '../types';

/**
 * Minimal helper used by the bond balance hooks to get the total PRANA volume.
 *
 * In this repo, the totals are available via `/bonds_v2.json` (generated by `scripts/scan-bonds-v2`).
 * We use that JSON instead of scanning `bonds(uint256)` on-chain (which requires knowing bond count).
 */
export const useBondsV2Volume = (): UseBondsV2VolumeResult => {
  const [buyBondTotalRawV2, setBuyBondTotalRawV2] = useState<bigint>(0n);
  const [sellBondTotalRawV2, setSellBondTotalRawV2] = useState<bigint>(0n);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [error, setError] = useState<unknown | null>(null);

  useEffect(() => {
    let cancelled = false;

    const run = async () => {
      setIsLoading(true);
      setError(null);

      try {
        // this will scan only *new* bonds and update the JSON files before we fetch totals.
        let refreshUpdated = false;
        try {
          // Use fetchJson so multiple hooks dedupe this GET request.
          // ensures new bonds are scanned before the cached JSON is reloaded
          const refreshResult = await fetchJson<{ updated?: boolean }>('/api/bonds-v2/refresh-bonds'); // checks if there's any new bonds
          refreshUpdated = Boolean(refreshResult?.updated);
        } catch {
          // ignore if the request fails
        }

        // If refresh found new bonds and updated JSON, force a refetch so we don't reuse a cached value.
        // Otherwise, reuse the shared cache to avoid duplicate requests on page load.
        const totals = await fetchBondsV2TotalsSafe({ force: refreshUpdated });
        if (!cancelled) {
          setBuyBondTotalRawV2(totals.buyBondTotalRawV2);
          setSellBondTotalRawV2(totals.sellBondTotalRawV2);
        }
      } catch (e: unknown) {
        if (!cancelled) {
          setError(e);
          setBuyBondTotalRawV2(0n);
          setSellBondTotalRawV2(0n);
        }
      } finally {
        if (!cancelled) setIsLoading(false);
      }
    };

    run();
    return () => {
      cancelled = true;
    };
  }, []);

  return { buyBondTotalRawV2, sellBondTotalRawV2, isLoading, error };
};
