import { useEffect, useMemo, useState } from 'react';
import { fetchJson } from '../utils/fetchJson';
import { fetchBondsV2JsonSafe } from '../utils/bondsV2Json';
import type {
  BondsV2Json,
  UseTotalV2BondPranaVolumeParams,
  UseTotalV2BondPranaVolumeResult,
} from '../types';

const safeLower = (value: unknown): string => (typeof value === 'string' ? value.toLowerCase() : '');

/**
 * Minimal helper used by the bond balance hooks to get the total PRANA volume.
 *
 * In this repo, the totals are available via `/bonds_v2.json` (generated by `scripts/scan-bonds-v2.js`).
 * We use that JSON instead of scanning `bonds(uint256)` on-chain (which requires knowing bond count).
 */
export const useTotalV2BondPranaVolume = ({
  contracts = [],
}: UseTotalV2BondPranaVolumeParams = {}): UseTotalV2BondPranaVolumeResult => {
  const [totalPranaRaw, setTotalPranaRaw] = useState<bigint>(0n);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [error, setError] = useState<unknown | null>(null);

  const addresses = useMemo(
    () => contracts.map((c) => safeLower(c?.address)).filter(Boolean),
    [contracts],
  );

  useEffect(() => {
    let cancelled = false;

    const run = async () => {
      setIsLoading(true);
      setError(null);

      try {
        // this will scan only *new* bonds and update the JSON files before we fetch totals.
        let refreshUpdated = false;
        try {
          // Use fetchJson so multiple hooks dedupe this GET request.
          // ensures new bonds are scanned before the cached JSON is reloaded
          const refreshResult = await fetchJson<{ updated?: boolean }>('/api/bonds-v2/refresh'); // checks if there's any new bonds
          refreshUpdated = Boolean(refreshResult?.updated);
        } catch {
          // ignore if the request fails
        }

        // If refresh found new bonds and updated JSON, force a refetch so we don't reuse a cached value.
        // Otherwise, reuse the shared cache to avoid duplicate requests on page load.
        const data = await fetchBondsV2JsonSafe<BondsV2Json>({}, { force: refreshUpdated });
        const buyAddress = safeLower(data?.buy?.address);
        const sellAddress = safeLower(data?.sell?.address);
        const buyTotalStr = data?.buy?.pranaAmount;
        const sellTotalStr = data?.sell?.pranaAmount;

        const buyTotalRaw = typeof buyTotalStr === 'string' ? BigInt(buyTotalStr) : 0n;
        const sellTotalRaw = typeof sellTotalStr === 'string' ? BigInt(sellTotalStr) : 0n;

        let sum = 0n;
        for (const addr of addresses) {
          if (addr === buyAddress) sum += buyTotalRaw;
          else if (addr === sellAddress) sum += sellTotalRaw;
        }

        if (!cancelled) setTotalPranaRaw(sum);
      } catch (e: unknown) {
        if (!cancelled) {
          setError(e);
          setTotalPranaRaw(0n);
        }
      } finally {
        if (!cancelled) setIsLoading(false);
      }
    };

    run();
    return () => {
      cancelled = true;
    };
  }, [addresses]);

  return { totalPranaRaw, isLoading, error };
};
