import { useEffect, useMemo, useState } from 'react';
import { fetchJson } from '../utils/fetchJson';

const safeLower = (value) => (typeof value === 'string' ? value.toLowerCase() : '');

/**
 * Minimal helper used by the bond balance hooks to get the total PRANA volume.
 *
 * In this repo, the totals are available via `/bonds_v2.json` (generated by `scripts/scan-bonds-v2.js`).
 * We use that JSON instead of scanning `bonds(uint256)` on-chain (which requires knowing bond count).
 */
export const useTotalBondPranaVolume = ({ contracts = [], fieldName = 'pranaAmount' } = {}) => {
  const [totalPranaRaw, setTotalPranaRaw] = useState(0n);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);

  const addresses = useMemo(
    () => contracts.map((c) => safeLower(c?.address)).filter(Boolean),
    [contracts],
  );

  useEffect(() => {
    let cancelled = false;

    const run = async () => {
      setIsLoading(true);
      setError(null);

      try {
        const data = await fetchJson('/bonds_v2.json');
        const buyAddress = safeLower(data?.buy?.address);
        const sellAddress = safeLower(data?.sell?.address);
        const buyTotalStr = data?.buy?.[fieldName];
        const sellTotalStr = data?.sell?.[fieldName];

        const buyTotalRaw = typeof buyTotalStr === 'string' ? BigInt(buyTotalStr) : 0n;
        const sellTotalRaw = typeof sellTotalStr === 'string' ? BigInt(sellTotalStr) : 0n;

        let sum = 0n;
        for (const addr of addresses) {
          if (addr === buyAddress) sum += buyTotalRaw;
          else if (addr === sellAddress) sum += sellTotalRaw;
        }

        if (!cancelled) setTotalPranaRaw(sum);
      } catch (e) {
        if (!cancelled) {
          setError(e);
          setTotalPranaRaw(0n);
        }
      } finally {
        if (!cancelled) setIsLoading(false);
      }
    };

    run();
    return () => {
      cancelled = true;
    };
  }, [addresses, fieldName]);

  return { totalPranaRaw, isLoading, error };
};


