import { useEffect, useMemo, useState } from 'react';
import { fetchJson } from '../utils/fetchJson';

const safeLower = (value) => (typeof value === 'string' ? value.toLowerCase() : '');
const PAGE_LOAD_CACHE_BUST = Date.now();

/**
 * Minimal helper used by the bond balance hooks to get the total PRANA volume.
 *
 * In this repo, the totals are available via `/bonds_v2.json` (generated by `scripts/scan-bonds-v2.js`).
 * We use that JSON instead of scanning `bonds(uint256)` on-chain (which requires knowing bond count).
 */
export const useTotalBondPranaVolume = ({ contracts = [], fieldName = 'pranaAmount' } = {}) => {
  const [totalPranaRaw, setTotalPranaRaw] = useState(0n);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);

  const addresses = useMemo(
    () => contracts.map((c) => safeLower(c?.address)).filter(Boolean),
    [contracts],
  );

  useEffect(() => {
    let cancelled = false;

    const run = async () => {
      setIsLoading(true);
      setError(null);

      try {
        // Best-effort: if the app is hosted with the optional Node server,
        // this will scan only *new* bonds and update the JSON files before we fetch totals.
        // On static hosting (no API), this will 404 and we simply fall back to the existing JSON.
        try {
          // Use fetchJson so multiple hooks dedupe this GET request.
          await fetchJson('/api/bonds-v2/refresh');
        } catch {
          // ignore
        }

        // Avoid stale caching if the JSON was just updated.
        // Use a stable cache-buster so multiple hook instances share one in-flight request.
        const data = await fetchJson(`/bonds_v2.json?t=${PAGE_LOAD_CACHE_BUST}`);
        const buyAddress = safeLower(data?.buy?.address);
        const sellAddress = safeLower(data?.sell?.address);
        const buyTotalStr = data?.buy?.[fieldName];
        const sellTotalStr = data?.sell?.[fieldName];

        const buyTotalRaw = typeof buyTotalStr === 'string' ? BigInt(buyTotalStr) : 0n;
        const sellTotalRaw = typeof sellTotalStr === 'string' ? BigInt(sellTotalStr) : 0n;

        let sum = 0n;
        for (const addr of addresses) {
          if (addr === buyAddress) sum += buyTotalRaw;
          else if (addr === sellAddress) sum += sellTotalRaw;
        }

        if (!cancelled) setTotalPranaRaw(sum);
      } catch (e) {
        if (!cancelled) {
          setError(e);
          setTotalPranaRaw(0n);
        }
      } finally {
        if (!cancelled) setIsLoading(false);
      }
    };

    run();
    return () => {
      cancelled = true;
    };
  }, [addresses, fieldName]);

  return { totalPranaRaw, isLoading, error };
};


